# Generated by Django 5.2.7 on 2025-11-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0002_client_equipment_newslettersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('under_review', 'تحت المراجعة'), ('responded', 'تم الرد'), ('completed', 'مكتمل')], default='new', max_length=50),
        ),
    ]
