# Generated by Django 5.2.7 on 2025-11-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0003_quoterequest_internal_notes_quoterequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('under_review', 'under review'), ('responded', 'responded'), ('completed', 'completed')], default='new', max_length=50),
        ),
    ]
